# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2025-04-04 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=500, null=True)),
                ('password', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Duanlianlog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=500, null=True)),
                ('kaluli', models.CharField(default='', max_length=500, null=True)),
                ('user', models.CharField(default='', max_length=500, null=True)),
                ('userid', models.CharField(default='', max_length=500, null=True)),
                ('shijian', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=500, null=True)),
                ('pic', models.CharField(default='', max_length=500, null=True)),
                ('neirong', models.CharField(default='', max_length=500, null=True)),
                ('shijian', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tizhong',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=500, null=True)),
                ('user', models.CharField(default='', max_length=500, null=True)),
                ('userid', models.CharField(default='', max_length=500, null=True)),
                ('shijian', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=500, null=True)),
                ('username', models.CharField(default='', max_length=500, null=True)),
                ('password', models.CharField(default='', max_length=500, null=True)),
                ('pic', models.CharField(default='', max_length=500, null=True)),
                ('gender', models.CharField(default='', max_length=500, null=True)),
                ('age', models.CharField(default='', max_length=500, null=True)),
                ('shengao', models.CharField(default='', max_length=500, null=True)),
                ('tizhong', models.CharField(default='', max_length=500, null=True)),
                ('tel', models.CharField(default='', max_length=500, null=True)),
                ('duanlian', models.CharField(default='', max_length=500, null=True)),
                ('xuqiu', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Xueya',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(default='', max_length=500, null=True)),
                ('userid', models.CharField(default='', max_length=500, null=True)),
                ('shuzhi', models.CharField(default='', max_length=500, null=True)),
                ('leixing', models.CharField(default='', max_length=500, null=True)),
                ('shijian', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Yao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=500, null=True)),
                ('user', models.CharField(default='', max_length=500, null=True)),
                ('userid', models.CharField(default='', max_length=500, null=True)),
                ('shijian', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Yinshi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(default='', max_length=500, null=True)),
                ('userid', models.CharField(default='', max_length=500, null=True)),
                ('shengyu', models.CharField(default='', max_length=500, null=True)),
                ('riqi', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Yinshilog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=500, null=True)),
                ('kaluli', models.CharField(default='', max_length=500, null=True)),
                ('shijian', models.CharField(default='', max_length=500, null=True)),
                ('user', models.CharField(default='', max_length=500, null=True)),
                ('userid', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
    ]
