# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2025-04-10 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('xitong', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bangding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zinv', models.CharField(default='', max_length=500, null=True)),
                ('zinvid', models.CharField(default='', max_length=500, null=True)),
                ('user', models.CharField(default='', max_length=500, null=True)),
                ('userid', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zinv',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=500, null=True)),
                ('username', models.CharField(default='', max_length=500, null=True)),
                ('password', models.CharField(default='', max_length=500, null=True)),
                ('sex', models.CharField(default='', max_length=500, null=True)),
                ('tel', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Yinshi',
        ),
        migrations.AddField(
            model_name='tizhong',
            name='shuju',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='yao',
            name='daka',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
