# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2025-05-02 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xitong', '0002_auto_20250410_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=500, null=True)),
                ('pic', models.CharField(default='', max_length=500, null=True)),
                ('content', models.CharField(default='', max_length=500, null=True)),
                ('addtime', models.CharField(default='', max_length=500, null=True)),
                ('clicknum', models.CharField(default='', max_length=500, null=True)),
                ('articletype', models.CharField(default='', max_length=500, null=True)),
                ('articletypeid', models.CharField(default='', max_length=500, null=True)),
                ('isreco', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Articlecomment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('article', models.CharField(default='', max_length=500, null=True)),
                ('articleid', models.CharField(default='', max_length=500, null=True)),
                ('user', models.CharField(default='', max_length=500, null=True)),
                ('userid', models.CharField(default='', max_length=500, null=True)),
                ('userpic', models.CharField(default='', max_length=500, null=True)),
                ('rootid', models.CharField(default='', max_length=500, null=True)),
                ('parentid', models.CharField(default='', max_length=500, null=True)),
                ('level', models.CharField(default='', max_length=500, null=True)),
                ('commenttime', models.CharField(default='', max_length=500, null=True)),
                ('isread', models.CharField(default='', max_length=500, null=True)),
                ('content', models.CharField(default='', max_length=500, null=True)),
                ('likenum', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Articletype',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collected',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(default='', max_length=500, null=True)),
                ('userid', models.CharField(default='', max_length=500, null=True)),
                ('article', models.CharField(default='', max_length=500, null=True)),
                ('articleid', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commentliked',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('articlecommentid', models.CharField(default='', max_length=500, null=True)),
                ('user', models.CharField(default='', max_length=500, null=True)),
                ('userid', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Healthrecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(default='', max_length=500, null=True)),
                ('userid', models.CharField(default='', max_length=500, null=True)),
                ('name', models.CharField(default='', max_length=500, null=True)),
                ('shangxian', models.CharField(default='', max_length=500, null=True)),
                ('xiaxian', models.CharField(default='', max_length=500, null=True)),
                ('danwei', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Liked',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(default='', max_length=500, null=True)),
                ('userid', models.CharField(default='', max_length=500, null=True)),
                ('article', models.CharField(default='', max_length=500, null=True)),
                ('articleid', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Likedmessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('likeduser', models.CharField(default='', max_length=500, null=True)),
                ('likeduserid', models.CharField(default='', max_length=500, null=True)),
                ('user', models.CharField(default='', max_length=500, null=True)),
                ('userid', models.CharField(default='', max_length=500, null=True)),
                ('isread', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Motiontype',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=500, null=True)),
                ('danwei', models.CharField(default='', max_length=500, null=True)),
                ('value', models.CharField(default='', max_length=500, null=True)),
                ('user', models.CharField(default='', max_length=500, null=True)),
                ('userid', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recordhealth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(default='', max_length=500, null=True)),
                ('userid', models.CharField(default='', max_length=500, null=True)),
                ('healthrecord', models.CharField(default='', max_length=500, null=True)),
                ('healthrecordid', models.CharField(default='', max_length=500, null=True)),
                ('shangxian', models.CharField(default='', max_length=500, null=True)),
                ('xiaxian', models.CharField(default='', max_length=500, null=True)),
                ('danwei', models.CharField(default='', max_length=500, null=True)),
                ('value', models.CharField(default='', max_length=500, null=True)),
                ('recordtime', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='bangding',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='zinv',
            name='pic',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
