# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2025-05-03 05:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xitong', '0003_auto_20250502_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bangding',
            old_name='status',
            new_name='status2',
        ),
    ]
