# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2025-05-03 05:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xitong', '0004_auto_20250503_0535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bangding',
            old_name='status2',
            new_name='status',
        ),
    ]
