# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2025-05-03 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xitong', '0005_auto_20250503_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='yao',
            name='date',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
