# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2025-05-03 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xitong', '0006_yao_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(default='', max_length=500, null=True)),
                ('authid', models.CharField(default='', max_length=500, null=True)),
                ('bloodpressure', models.BooleanField(default=True)),
                ('tizhong', models.BooleanField(default=True)),
                ('xuqiu', models.BooleanField(default=True)),
                ('duanlian', models.BooleanField(default=True)),
                ('diet', models.BooleanField(default=True)),
                ('exercise', models.BooleanField(default=True)),
                ('medicine', models.BooleanField(default=True)),
            ],
        ),
    ]
